#!/usr/bin/env bash

echo 'Working with OrientDB'
cd $HOME/Downloads/orientdb-community-importers-2.2.37/bin
./console.sh <<EOF


CONNECT remote:localhost/GratefulDeadConcerts root P@ssword10 





EOF

